### ISSUE TITLE
How do i use.

### ISSUE THREAD

**Issue by mynameisisaac** [NotNanook/Ascendit-Raot#2]
How can I download these cheats?

**Comment by NotNanook** [comment]
If you cant build a dll by yourself, i cant help you

**Comment by NotNanook** [comment]
or just use the launcher

**Comment by mynameisisaac** [comment]
And how do i download the launcher?

**Comment by Anon121334** [comment]
can you elaborate on "just use the launcher" please
where do we put which files?

**Comment by rqmaot** [comment]
You can build the dll using Visual Studio and inject it into the game using Cheat Engine.
But the only things that seem to be implemented are infinite gas and stress which are almost trivial to make yourself using Cheat Engine so I wouldn't bother. The project as it is is more an exercise in C++ cheating than a real cheat client, and it may not be developed any further.
Still if you're that dedicated to it you just need to install Visual Studio on your computer and open Ascendit-Raot.vcxproj with it, then build the dll-- you'll have to set it to Release x64 and go to Build > Build Ascendit-Raot, the dll will get made in [Ascendit-Raot-master]/x64/Release (you can build it without VS but as there's a project file to do it that way it's the easiest way especially considering you probably don't know how to use a terminal). Then install Cheat Engine (you'll need to add an exception for it in your antivirus), attach it to the game, then go to Memory View > Tools > Inject DLL and inject Ascendit-Raot.dll. The hotkey for infinite gas is K and the hotkey for infinite stress is I (you can find the hotkeys for implemented cheats in their source, it's the char used in the setKey function).
Again it's not really worth it, I'm just putting a complete explanation here so that you can figure that out for yourself quicker. If you want to cheat then learn how to use cheat engine.

**Comment by Anon121334** [comment]
is it possible for you to just post the cheat engine release? when I open the project, there's no code, but when i open other things such as gas, it loads the code ;-;
![Screenshot 2022-11-04 085002](https://user-images.githubusercontent.com/117452281/199976554-895a5a9e-088d-4431-bb3c-871a86febeb8.png)
![image](https://user-images.githubusercontent.com/117452281/199976601-bc6f3249-4e56-47bb-9ef2-1f0b045d80a6.png)

**Comment by rqmaot** [comment]
*sigh*
https://rqmaot.github.io/raot/hax/ascendit/

**Comment by mynameisisaac** [comment]
Hey, Rqmaot, the esp isn't working? I'm pressing I and when that doesn't
work, I try num lock 4, but it still doesn't work.

**Comment by rqmaot** [comment]
The ESP isn't implemented. You can see in the code that OnEnable is empty (or rather its contents have been commented out, though what's there wouldn't be ESP). Also I is the key for infinite stress, not ESP

**Comment by mynameisisaac** [comment]
Ah ok, I see, So the infinite stress and infinite gas are the only two
things that work?

**Comment by rqmaot** [comment]
Yes, as far as I can tell

**Comment by NotNanook** [comment]
Isaac is the reason why im slowly getting less and less helpfull when it comes to cheating in games. There are almost no people out there who actually want to LEARN. Its mind-boggling and my braincells are slowly dying. Thank you rqmaot. Yes, you are right. This version doesnt have a working rapid-firing nor esp module. They are both left as to be completed by the user. Its really not that hard if someone actually tries. I simply didnt upload it. Anyway, have a good day and im tbh suprised that this many people have been interested in a raot cheat

**Comment by Anon121334** [comment]
TBH, this stuff is far above my level, it would take me a while to learn it, and in between the college and the work, i just want a lil fun with the cheat. I'm not a noob, been playing for a few months, but i just wanted a shortcut really. If its possible I can throw some money your way and you can release the complete thing, but all of my education is on making a lot of money, and my brain is split enough already ;-;   in short, I'm sorry if I made you feel not good but this is the way of the world, my world at least

**Comment by rqmaot** [comment]
NotNanook yeah it be like that but it does make some sense that most of the people looking for cheats online would be doing so because they want shortcuts and not because they want to do the hard learning

Anon, I don't recommend cheating without learning how it works for a number of reasons, the game is fun enough without cheating, but if you really want to you have ascendit's infinite gas and stress. I also have some scripts at https://rqmaot.github.io/raot/hax/ although I think everything ammo related broke as of 2.085 (it was already buggy to begin with), there's still working infinite gas and stress and primitive teleporting. What I'd actually recommend is going through the Cheat Engine tutorial, looking at the scripts, and reading some on the CE forums to learn how it works and then you can improve on them or make your own, which is far more rewarding than using an infinite gas script you don't understand imo
